name: me_app_mobile
description: "ME App - your personal nutrition assistant"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  device_info_plus: ^9.1.2
  # Для уведомлений и фоновых задач
  flutter_local_notifications: ^17.2.1+2
  flutter_background_service: ^5.0.10
  # Для работы с timezone
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
